# Auto-generated by fast_finetune_pipeline.py
import os, sys, json
from pathlib import Path
sys.path.insert(0, '/root/24BCE5561_samsung/26ARS05VITC_Quantum-inspired_Annealing_for_Multi-stage_Reasoning')

# Must run before torch -- or anything that imports torch, including
# unsloth -- is ever imported: once a CUDA context exists the visible device
# list is fixed for the process. Without this, HF's Trainer resolves its own
# training device independently of wherever we later place the model
# (device_map/.to()) and lands on cuda:0 regardless, which OOMs if cuda:0
# happens to be the saturated card on a shared machine.
from pipeline.device_utils import mask_cuda_visible_devices, resolve_device
DEVICE_ARG = None
mask_cuda_visible_devices(DEVICE_ARG)

import torch
import yaml
import inspect
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM, AutoTokenizer,
    BitsAndBytesConfig, TrainingArguments,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer
try:
    from trl import SFTConfig as _TrainCls
except ImportError:
    _TrainCls = TrainingArguments
USE_UNSLOTH = False

TRAIN_FILE  = 'data/curation/greedy/finetune_train.jsonl'
VAL_FILE    = 'data/curation/greedy/finetune_val.jsonl'
ADAPTER_OUT = '/root/24BCE5561_samsung/26ARS05VITC_Quantum-inspired_Annealing_for_Multi-stage_Reasoning/checkpoints/curate-greedy/final_adapter'
RUN_NAME    = 'curate-greedy'
CONFIG_PATH = '/root/24BCE5561_samsung/26ARS05VITC_Quantum-inspired_Annealing_for_Multi-stage_Reasoning/config/config.yaml'
EPOCHS      = 3
LR          = 0.0001
BATCH_SIZE  = 4
LORA_RANK   = 32
LORA_ALPHA  = 64
RESUME      = False
FORCE_4BIT  = False
GEN_EVAL_N  = 0
QUALITY_THRESHOLD = 0.70   # Only train on QUBO examples with high correctness score

with open(CONFIG_PATH) as f:
    cfg = yaml.safe_load(f)

model_name  = cfg["model"]["name"]
cache_dir   = cfg["model"].get("cache_dir")
train_cfg   = cfg.get("training", {})
max_seq     = train_cfg.get("max_seq_length", 2048)
lora_drop   = train_cfg.get("lora_dropout", 0.05)
target_mods = train_cfg.get("lora_target_modules", ["q_proj", "v_proj", "k_proj", "o_proj"])

# ── Step 1: Load tokenizer first (needed for correct chat template formatting) ──
print(f"[SFT] Loading tokenizer for {model_name} ...")
tokenizer = AutoTokenizer.from_pretrained(model_name, cache_dir=cache_dir)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# ── Step 2: Load & quality-filter training data ──────────────────────────
def load_jsonl(fpath):
    rows = []
    p = Path(fpath)
    if not p.exists():
        return rows
    with open(p, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows

def is_quality(rec):
    """Keep only high-quality QUBO-selected reasoning examples."""
    meta = rec.get("metadata", {})
    if not meta.get("qubo_selected", False):
        return False   # drops OpenOrca and any non-QUBO examples
    score = meta.get("correctness_score", 0.0) or 0.0
    return score >= QUALITY_THRESHOLD

def to_text(rec):
    """Convert message list to text using the model's own chat template (Llama-3.2)."""
    msgs = rec.get("messages", [])
    if not msgs:
        return ""
    try:
        return tokenizer.apply_chat_template(
            msgs,
            tokenize=False,
            add_generation_prompt=False,
        )
    except Exception:
        # Fallback: plain concatenation
        parts = []
        for m in msgs:
            role, content = m.get("role", ""), m.get("content", "")
            parts.append(f"{role}: {content}")
        return "\n".join(parts)

print(f"[SFT] Loading {TRAIN_FILE} ...")
train_raw = load_jsonl(TRAIN_FILE)
val_raw   = load_jsonl(VAL_FILE)
print(f"[SFT] Raw   Train={len(train_raw)}  Val={len(val_raw)}")

# Apply quality filter
train_raw = [r for r in train_raw if is_quality(r)]
val_raw   = [r for r in val_raw   if is_quality(r)]
print(f"[SFT] After quality filter (score>={QUALITY_THRESHOLD}, qubo_selected=True): Train={len(train_raw)}  Val={len(val_raw)}")

train_texts = [t for t in (to_text(r) for r in train_raw) if len(t) > 20]
val_texts   = [t for t in (to_text(r) for r in val_raw)   if len(t) > 20]
print(f"[SFT] Final Train={len(train_texts)}  Val={len(val_texts)}")

if not train_texts:
    print("[ERROR] No training examples after filtering. Check data/finetune_train.jsonl.")
    sys.exit(1)

train_ds = Dataset.from_dict({"text": train_texts})
val_ds   = Dataset.from_dict({"text": val_texts}) if val_texts else None

# Optional per-epoch generation probe. Off by default: a probe small enough to
# run every epoch has a confidence interval tens of points wide, so it cannot
# rank two training runs against each other -- and it used to also SELECT which
# epoch got saved (load_best_model_at_end below), which handed each arm of a
# comparison its own independent upward nudge from noise. Real accuracy is
# measured once, on a held-out set, by scripts/compare_curation_arms.py.
val_raw_gsm8k = [r for r in val_raw if r.get("metadata", {}).get("source") == "gsm8k"]
if not val_raw_gsm8k:
    val_raw_gsm8k = val_raw # Fallback if no gsm8k specifically
val_raw_eval = val_raw_gsm8k[:GEN_EVAL_N] if GEN_EVAL_N > 0 else []

# ── Step 3: Load model ────────────────────────────────────────────────
# Auto-picks whichever visible GPU currently has the most free VRAM instead
# of torch.cuda.current_device() (which is just whichever card happens to be
# device 0), so a busy card on a shared machine isn't where this lands.
device = resolve_device(DEVICE_ARG)
use_cuda = device.type == "cuda"
if use_cuda:
    # Also covers the Unsloth path below, which has no device_map kwarg and
    # otherwise defaults to whatever torch.cuda.current_device() is.
    torch.cuda.set_device(device.index or 0)
use_bf16 = use_cuda and torch.cuda.is_bf16_supported()

# 4-bit was unconditional on CUDA, which is the right default for a consumer
# card and the wrong one for an 80GB H100: a 3B model is ~6GB in bf16, so
# quantising buys nothing and costs accuracy plus the bitsandbytes/accelerate
# interaction that broke loading. FORCE_4BIT respects an explicit --4bit; the
# default now quantises only when the visible GPU is genuinely small.
if not use_cuda:
    use_4bit = False
elif FORCE_4BIT:
    use_4bit = True
else:
    _vram_gb = torch.cuda.get_device_properties(device.index or 0).total_memory / 1e9
    use_4bit = _vram_gb < 24.0
    print(f"[SFT] GPU has {_vram_gb:.0f} GB -> "
          f"{'4-bit QLoRA' if use_4bit else 'bf16 LoRA (no quantisation needed)'}")

peft_cfg = None   # set below on the non-Unsloth path; stays None when Unsloth
                  # has already returned a PEFT-wrapped model, so SFTTrainer
                  # is not asked to wrap it a second time.

if USE_UNSLOTH:
    # FastLanguageModel.from_pretrained loads the base model AND applies
    # Unsloth's patched attention/RoPE/RMSNorm kernels in one call; the 4-bit
    # path and dtype selection are handled internally rather than via a
    # separate BitsAndBytesConfig.
    print(f"[SFT] Loading {model_name} via Unsloth (4-bit={use_4bit}, bf16={use_bf16}) ...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_name,
        max_seq_length=max_seq,
        dtype=torch.bfloat16 if use_bf16 else (torch.float16 if use_cuda else torch.float32),
        load_in_4bit=use_4bit,
        cache_dir=cache_dir,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # get_peft_model here plays the same role as LoraConfig + SFTTrainer's
    # peft_config below on the non-Unsloth path, except the wrapping happens
    # now rather than inside the trainer -- so peft_cfg is left None and must
    # NOT be passed to SFTTrainer, or the model would be peft-wrapped twice.
    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_RANK,
        lora_alpha=LORA_ALPHA,
        target_modules=target_mods,
        lora_dropout=lora_drop,
        bias="none",
        # Unsloth's own gradient checkpointing implementation; this is the
        # main source of its reported VRAM reduction over vanilla PEFT GC.
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )
else:
    bnb_config = None
    if use_4bit:
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16 if use_bf16 else torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
        )

    print(f"[SFT] Loading {model_name} (4-bit={use_4bit}, bf16={use_bf16}) ...")
    # device_map pins every module to ONE gpu rather than "auto".
    #
    # "auto" lets accelerate split the model and spill whatever does not fit to
    # CPU/disk. bitsandbytes 4-bit refuses that split and aborts with
    # "Some modules are dispatched on the CPU or the disk", which is what killed
    # all three curation runs. A 3B model is small enough to sit entirely on one
    # card in either precision, so there is nothing to gain from sharding, and
    # pinning turns a genuine capacity problem into an honest OOM instead of a
    # silent offload.
    mkw = {
        "cache_dir":   cache_dir,
        "device_map":  {"": device.index or 0} if use_cuda else None,
        "torch_dtype": torch.bfloat16 if use_bf16 else (torch.float16 if use_cuda else torch.float32),
        "low_cpu_mem_usage": True,
    }
    if bnb_config:
        mkw["quantization_config"] = bnb_config

    model = AutoModelForCausalLM.from_pretrained(model_name, **mkw)

    if use_4bit:
        model = prepare_model_for_kbit_training(model)

    # ── Step 4: LoRA config ─────────────────────────────────────────────
    peft_cfg = LoraConfig(
        r=LORA_RANK,
        lora_alpha=LORA_ALPHA,
        target_modules=target_mods,
        lora_dropout=lora_drop,
        bias="none",
        task_type="CAUSAL_LM",
    )

os.makedirs(ADAPTER_OUT, exist_ok=True)
run_dir = str(Path(ADAPTER_OUT).parent)

grad_accum = max(1, 8 // BATCH_SIZE)

# Introspect _TrainCls at runtime so the script works regardless of trl version.
_sig = inspect.signature(_TrainCls.__init__).parameters

_eval_kw   = "eval_strategy" if "eval_strategy" in _sig else "evaluation_strategy"
_maxlen_kw = next((k for k in ("max_seq_length", "max_length") if k in _sig), None)
_txtfld_in_cfg = "dataset_text_field" in _sig

_cfg = {
    "output_dir": run_dir,
    "per_device_train_batch_size": BATCH_SIZE,
    "per_device_eval_batch_size": BATCH_SIZE,
    "gradient_accumulation_steps": grad_accum,
    "learning_rate": LR,
    "warmup_ratio": 0.05,
    "num_train_epochs": EPOCHS,
    "bf16": use_bf16,
    "fp16": use_cuda and not use_bf16,
    "logging_steps": 10,
    "save_strategy": "epoch",
    _eval_kw: "epoch",
    # No load_best_model_at_end: every arm keeps its FINAL epoch, so the arms
    # differ only in their training data and not in which checkpoint luck
    # happened to favour. Selecting on eval_gsm8k_accuracy over a few dozen
    # questions is selecting on noise, and it biases each arm upward by a
    # different random amount -- which is exactly what makes a multi-arm
    # comparison unfalsifiable. eval_loss is still logged per epoch for the
    # loss curve; it just does not decide anything.
    "remove_unused_columns": False,
    "report_to": "none",
    "run_name": RUN_NAME,
    "dataloader_num_workers": 0,
    "optim": "paged_adamw_8bit" if use_cuda else "adamw_torch",
}
if _txtfld_in_cfg:
    _cfg["dataset_text_field"] = "text"
if _maxlen_kw:
    _cfg[_maxlen_kw] = max_seq

training_args = _TrainCls(**_cfg)

_sft_sig = inspect.signature(SFTTrainer.__init__).parameters
_extra = {}
if not _txtfld_in_cfg and "dataset_text_field" in _sft_sig:
    _extra["dataset_text_field"] = "text"
if not _maxlen_kw and "max_seq_length" in _sft_sig:
    _extra["max_seq_length"] = max_seq

# trl >= 0.12 renamed 'tokenizer' to 'processing_class'
if "processing_class" in _sft_sig:
    _extra["processing_class"] = tokenizer
elif "tokenizer" in _sft_sig:
    _extra["tokenizer"] = tokenizer

if "peft_config" in _sft_sig and peft_cfg is not None:
    # peft_cfg is None on the Unsloth path -- the model there is already
    # PEFT-wrapped by FastLanguageModel.get_peft_model above, and wrapping it
    # again here would double-apply LoRA.
    _extra["peft_config"] = peft_cfg

# Subclass SFTTrainer to compute custom accuracy metric
import re
from math import sqrt

def _wilson95(k, n, z=1.96):
    """Wilson score interval -- behaves sanely at small n and near 0/1,
    where the normal approximation runs off the end of [0, 1]."""
    if n == 0:
        return 0.0, 0.0
    p = k / n
    d = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / d
    half = z * sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return max(0.0, centre - half), min(1.0, centre + half)

class CustomAccTrainer(SFTTrainer):
    def __init__(self, *args, val_raw_data=None, tokenizer=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.val_raw_data = val_raw_data
        self.gen_tokenizer = tokenizer
        self.epoch_accuracies = []

    def evaluate(self, eval_dataset=None, ignore_keys=None, metric_key_prefix="eval"):
        metrics = super().evaluate(eval_dataset, ignore_keys, metric_key_prefix)
        if not self.val_raw_data:
            return metrics
            
        print("\n[Eval] Running generation on GSM8K val subset for accuracy...")
        self.model.eval()
        correct = 0
        total = len(self.val_raw_data)
        
        for item in self.val_raw_data:
            # Reconstruct prompt (all but last assistant message)
            msgs = item.get("messages", [])
            prompt_msgs = [m for m in msgs if m["role"] != "assistant"]
            prompt_str = self.gen_tokenizer.apply_chat_template(prompt_msgs, tokenize=False, add_generation_prompt=True)
            
            inputs = self.gen_tokenizer(prompt_str, return_tensors="pt").to(self.model.device)
            with torch.no_grad():
                out_ids = self.model.generate(
                    **inputs,
                    max_new_tokens=256,
                    do_sample=False,
                    pad_token_id=self.gen_tokenizer.eos_token_id
                )
            gen_text = self.gen_tokenizer.decode(out_ids[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
            
            gold = str(item.get("metadata", {}).get("gold", "")).strip()
            # Extract number from gen_text
            gen_text = gen_text.replace(",", "")
            nums = re.findall("-?\\d+(?:\\.\\d+)?", gen_text)
            pred_num = float(nums[-1]) if nums else None
            
            try:
                gold_num = float(gold)
            except ValueError:
                gold_num = None
                
            if pred_num is not None and gold_num is not None and abs(pred_num - gold_num) <= 1e-4:
                correct += 1
                
        acc = correct / total if total > 0 else 0.0
        metrics[f"{metric_key_prefix}_gsm8k_accuracy"] = acc
        self.epoch_accuracies.append(acc)
        # Print the interval, not just the point estimate -- at these sample
        # sizes the interval is wide enough that two arms differing by several
        # points are indistinguishable, and showing only "35%" invites reading
        # a coin flip as a finding.
        lo, hi = _wilson95(correct, total)
        print(f"[Eval] Epoch GSM8K probe: {acc:.1%} ({correct}/{total})  "
              f"95% CI [{lo:.1%}, {hi:.1%}]  -- probe only, does not select the checkpoint\n")
        return metrics

print(f"[SFT] Training {len(train_texts)} examples for {EPOCHS} epoch(s) | rank={LORA_RANK} alpha={LORA_ALPHA} lr={LR} ...")
trainer = CustomAccTrainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    val_raw_data=val_raw_eval,
    tokenizer=tokenizer,
    **_extra,
)

# Resume from the newest per-epoch checkpoint in run_dir if one is present.
# save_strategy="epoch" already writes them; without this a crash at epoch 4 of 5
# would restart from zero.
_resume_ckpt = None
if RESUME:
    try:
        from transformers.trainer_utils import get_last_checkpoint
        if os.path.isdir(run_dir):
            _resume_ckpt = get_last_checkpoint(run_dir)
    except Exception as _e:
        print(f"[SFT] Could not look for a checkpoint to resume ({_e}).")
    if _resume_ckpt:
        print(f"[SFT] Resuming from checkpoint: {_resume_ckpt}")
    else:
        print("[SFT] No existing checkpoint found; starting fresh.")

trainer.train(resume_from_checkpoint=_resume_ckpt)

# A one-epoch uptick in the probe is almost never signal -- with a few dozen
# questions a single question moves the number by several points -- so this
# only speaks up when the last epoch clears the previous epoch's upper
# confidence bound, i.e. when the rise is larger than the probe's own noise.
accs = trainer.epoch_accuracies
if len(accs) >= 2 and val_raw_eval:
    _n = len(val_raw_eval)
    _prev_hi = _wilson95(round(accs[-2] * _n), _n)[1]
    if accs[-1] > _prev_hi:
        print("\n" + "!" * 60)
        print(f"⚠️  Probe rose from {accs[-2]:.1%} to {accs[-1]:.1%} on the last epoch,")
        print(f"⚠️  clearing the previous epoch's 95% upper bound ({_prev_hi:.1%}).")
        print("⚠️  Consider more epochs -- then confirm on the held-out set.")
        print("!" * 60 + "\n")

trainer.save_model(ADAPTER_OUT)
tokenizer.save_pretrained(ADAPTER_OUT)
print(f"[SFT] Adapter saved to {ADAPTER_OUT}")
